
const plans = [
  // Advertisement Plans
  {
    label: "Premium - 1Y Validity",
    value: "1999",
    duration: { years: 1 },
    subscription: "advertisement",
  },
  {
    label: "Platinum - 1Y Validity",
    value: "999",
    duration: { years: 1 },
    subscription: "advertisement",
  },
  {
    label: "Gold - 6M Validity",
    value: "800",
    duration: { months: 6 },
    subscription: "advertisement",
  },
  {
    label: "Silver - 3M Validity",
    value: "500",
    duration: { months: 3 },
    subscription: "advertisement",
  },

  // Market Place Plans
  {
    label: "Premium - 2M Validity",
    value: "500",
    duration: { months: 2 },
    subscription: "marketFeed",
  },
  {
    label: "Standard - 2M Validity",
    value: "300",
    duration: { months: 2 },
    subscription: "marketFeed",
  },

  // Blaunk Dial Plans
  {
    label: "Premium - 1Y Validity",
    value: "1999",
    duration: { years: 1 },
    subscription: "blaunkDial",
  },
  {
    label: "Platinum - 1Y Validity",
    value: "999",
    duration: { years: 1 },
    subscription: "blaunkDial",
  },
  {
    label: "Gold - 6M Validity",
    value: "800",
    duration: { months: 6 },
    subscription: "blaunkDial",
  },
  {
    label: "Silver - 3M Validity",
    value: "500",
    duration: { months: 3 },
    subscription: "blaunkDial",
  },
];

const adTypes: Record<string, string[]> = {
  homePage: ["Business Card", "Slider", "Category", "Deal & Offer", "Explore"],
  bgt: ["Running ad", "Slider"],
  tour: ["Deal & Offer", "Explore"],
  cake: ["Deal & Offer", "Explore"],
  store: ["Deal & Offer", "Explore"],
  boutique: [
    "Women's collection",
    "Men's collection",
    "Style on rent",
    "Deal & Offer",
    "Explore",
    "Indian Celebrity Designer",
    "International Celebrity Designer",
  ],
};

const services: Record<string, string[]> = {
  healthcare: [
    "Hair Salon",
    "Spa",
    "Ayurvedic Spa",
    "Physiotherapist",
    "Others",
  ],
  artists: [
    "Henna Artist",
    "Tattoo Artist",
    "Makeup Artist",
    "Nail Artist",
    "Saree Draper",
    "Costume Designer",
    "Sketch Artist",
    "Portrait",
    "Sculptor",
    "Clay Artist",
    "Others",
  ],
  prediction: [
    "Pandit",
    "Priest",
    "Astrologer",
    "Palmistry",
    "Vastu",
    "Tarot Reader",
    "Numerologist",
    "Gemologist",
    "Others",
  ],
  transport: [
    "Packers & Movers",
    "Driver",
    "Fleet Agent",
    "Transporters",
    "Vehicle on rent",
    "Custom Agent",
    "Courier Services",
    "Logistics",
    "Cargo Services",
    "Others",
  ],
  mechanic: [
    "Mechanic by night",
    "All Engine Service",
    "Truck Ecm Repair",
    "Breakdown Services",
    "Bike Repairs",
    "Car Repairs",
    "Car Electrical Service",
    "Car Battery Repair",
    "Accident Towing",
    "Others",
  ],
  event: [
    "Workshops",
    "Comedy Shows",
    "Screenings",
    "Spirituality",
    "Exhibition",
    "Meetups",
    "Kids",
    "Performances",
    "Talks",
    "Festivals",
    "Conferences",
    "Sports",
    "Competitions",
    "Others",
  ],
  eventMgt: [
    "Inhouse decorator",
    "Outdoor decorator",
    "Wedding Planner",
    "Orchestra",
    "Balloon Arch",
    "Balloon Backdrop",
    "Sound Systems",
    "Flower Decorators",
    "Event Organizers",
    "Birthday Party Organizers",
    "Tent House",
    "Costumes on rent",
    "Office Decorators",
    "Caterers",
    "Pre wedding shoot",
    "Car decoration",
    "Pandit",
    "Anchoring Services",
    "Photographers",
    "Advertising agencies",
    "DJ",
    "Venue Selection",
    "Others",
  ],
  itDevelopers: [
    "Web Developer",
    "WordPress Developer",
    " Software Engineer",
    "Front-End Developer",
    "Mobile Application Developer",
    "Game Developer",
    "Back-End Developer",
    "Big Data Developer",
    "Developmental Operations Engineer",
    "Data Scientist",
    "Security Developer",
    "Graphics Developer",
    "Language developer",
    "Desktop developer",
    "Software developer",
    "Operating systems developer",
    "Embedded systems developer",
    "CRM developer",
    "Full stack developer",
    "Software Tester",
    "MERN Developer",
    "UI/UX Designer",
    "Others",
  ],
  property: [
    "Real Estate Agent",
    "Property Dealers",
    "Property Developers",
    "Property Consultants",
    "Property Valuers",
    "Property Registration Consultants",
    "Property Lawyers",
    "Others",
  ],
  tour: [
    "Flight Booking",
    "Bus Booking",
    "Railway Booking",
    "Hotel Booking",
    "Domestic Package",
    "International Package",
    " Others",
  ],
  helper: [
    "House Cook",
    "House Maid",
    "Gardener",
    "Electrician",
    "Plumber",
    "Carpenter",
    "Others",
  ],
  misc: ["Gym", "Music", "Others"],
};

const products: Record<string, string[]> = {
  clubAndResort: ["Used membership", "New (Agent)"],
  property: [
    "For Sale",
    "On Lease Office",
    "On Lease House",
    "Land commercial",
    "Land Agriculture",
    "For Rent",
    "Fully furnished house",
    "Semi-furnished House",
    "Pent house",
    "Sharing office",
    "Fully furnished office",
    "Farm house",
    "Apartment",
    "Mall Shop On Rent",
    "Villa",
    "Independent House",
    "Residential Plot",
    "Bungalow",
    "Paying Guest",
  ],
  appliances: [
    "Kitchen appliances",
    "Hotel appliances",
    "Office appliances",
    "Electronic appliances",
    "Others",
  ],
  usedVehicle: [
    "2 wheeler",
    "Auto",
    "Car",
    "Mini Truck",
    "EV",
    "Spare parts",
    "Others",
  ],
  d2h: ["Connection", "Service", "Spares", "Others"],
  misc: ["Books", "Sports", "Gym", "Musical Instruments", "Others"],
};

const groupOptions: string[] = [
  "Education",
  "Accessories",
  "Agro -Dry fruits",
  "Agro -Fruits",
  "Agro -Grains",
  "Agro -Seeds",
  "Agro -Spices",
  "Agro -Veggies",
  "AGRO-Fertilizer",
  "Apparel -Kids",
  "Apparel -Men",
  "Apparel -Women",
  "Art and Gallery",
  "Bathroom Accessories",
  "Books",
  "Chemicals",
  "Cleaners",
  "Computer",
  "Construction",
  "Cosmetic -Women",
  "Cosmetic -Men",
  "cosmetics-Kids",
  "Electrical",
  "Electronics",
  "Food and Beverages",
  "Footwear",
  "Gardening",
  "Handmade",
  "Hardware",
  "Heavy Tools",
  "Herbal Nutrition",
  "Kitchen Appliances",
  "Kitchen ware",
  "Machinery",
  "Packaging",
  "Plastic Ware",
  "Sports",
  "Stationery",
  "Textile Fabrics",
  "Threads and Laces",
  "Toys",
  "Vehicle Operator",
  "Jewellers",
  "IT Developer",
  "Services",
  "Tourism",
];


export { plans, adTypes, services, products, groupOptions };